---
title: "SMN-risk: an update from the Hodgkin Lymphoma survivorship cohort"
author: "Gordon P. Watt, PhD"
date: "`Sys.Date()`"
execute:
  echo: false
  warning: false
  error: false
  message: false
format: "docx"


---

```{r}

#| label: load-packages

library(tidyverse)
library(readxl)
library(stringr)

knitr::opts_chunk$set(warning = F, error = F, message = F, echo = F)

```

```{r}

#| label: read-data

if (file.exists("U://HL/SMN-risk/secure_data/2024-08-20 Research Hodgkin cohort.xlsx")) {
  # tries Windows MDW version first
dta0 <- readxl::read_xlsx("U://HL/SMN-risk/secure_data/2024-08-20 Research Hodgkin cohort.xlsx")
} else {
  # then reads Mac Volumes
  dta0 <- readxl::read_xlsx("/Volumes/g.watt/HL/SMN-risk/secure_data/2024-08-20 Research Hodgkin cohort.xlsx")
}


```


```{r}

#| label: prepare-outcome-variables

# dictionary for 2nd cancer sites

smn_morphs = unique(c(unique(dta0$smn1_morph), unique(dta0$smn2_morph),
                    unique(dta0$smn3_morph), unique(dta0$smn4_morph),
                    unique(dta0$smn5_morph), unique(dta0$smn6_morph),
                    unique(dta0$smn7_morph)))
write.csv(smn_morphs, "./output/intermediate-files/smn_morphs_list.csv", row.names = F)

dta1 = dta0 %>% mutate(
  
  # recode y_livedead 9999 and 9998 as na
  # note - y_lcontact is the most recent date to which SMN would be known. So
  # censoring should happen no later than that date. 
  
  y_livedead = ifelse(
    y_livedead %in% c(9998,9999), NA_real_, y_livedead
  )
  ) %>% tidyr::unite(
  
  # create date variables
  
  dob, c(m_birth, y_birth), sep = "-", remove = F
) %>% tidyr::unite(
  ddx, c(m_diagnose, y_diagnose), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn1, c(m_smn1, y_smn1), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn2, c(m_smn2, y_smn2), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn3, c(m_smn3, y_smn3), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn4, c(m_smn4, y_smn4), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn5, c(m_smn5, y_smn5), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn6, c(m_smn6, y_smn6), sep = "-", remove = F
) %>% tidyr::unite(
  d_smn7, c(m_smn7, y_smn7), sep = "-", remove = F
) %>% mutate(
  dob = lubridate::parse_date_time(dob, "my"),
  ddx = lubridate::parse_date_time(ddx, "my"),
  d_smn1 = lubridate::parse_date_time(d_smn1, "my"),
  d_smn2 = lubridate::parse_date_time(d_smn2, "my"),
  d_smn3 = lubridate::parse_date_time(d_smn3, "my"),
  d_smn4 = lubridate::parse_date_time(d_smn4, "my"),
  d_smn5 = lubridate::parse_date_time(d_smn5, "my"),
  d_smn6 = lubridate::parse_date_time(d_smn6, "my"),
  d_smn7 = lubridate::parse_date_time(d_smn7, "my"),
  
  # indicator for malignant only
  
  smn1_mal = ifelse(smn1_behav %in% c(3,6,9),1,0),
  smn2_mal = ifelse(smn2_behav %in% c(3,6,9),1,0), 
  smn3_mal = ifelse(smn3_behav %in% c(3,6,9),1,0),
  smn4_mal = ifelse(smn4_behav %in% c(3,6,9),1,0),
  smn5_mal = ifelse(smn5_behav %in% c(3,6,9),1,0),
  smn6_mal = ifelse(smn6_behav %in% c(3,6,9),1,0),
  smn7_mal = ifelse(smn7_behav %in% c(3,6,9),1,0),
  
  # date of first malignant smn
  
  d_1st_inv = case_when(
    smn1_mal == 1 ~ d_smn1,
    smn1_mal == 0 & smn2_mal == 1 ~ d_smn2,
    smn1_mal == 0 & smn2_mal == 0 &
      smn3_mal == 1 ~ d_smn3,
    smn1_mal == 0 & smn2_mal == 0 &
      smn3_mal == 0 & smn4_mal ==1 ~ d_smn4,
    smn1_mal == 0 & smn2_mal == 0 &
      smn3_mal == 0 & smn4_mal == 0 &
      smn5_mal == 1 ~ d_smn5,
    smn1_mal == 0 & smn2_mal == 0 &
      smn3_mal == 0 & smn4_mal == 0 &
      smn5_mal == 0 & smn6_mal == 1 ~ d_smn6,
    smn1_mal == 0 & smn2_mal == 0 &
      smn3_mal == 0 & smn4_mal == 0 &
      smn5_mal == 0 & smn6_mal == 0 & 
      smn7_mal == 1 ~ d_smn7
  ),
  
  # categories for SMN site
  
  # first, make numeric vars
  across(
      .cols = contains("_site"),
      .fns = ~as.numeric(stringr::str_remove(., "C")),
      .names = "{.col}_num"
      ),
  across(
    .cols = contains("_num"),
    .fns = ~case_when(
     (. < 150) | (. >= 300 & . <338) | (.==760) ~ "Head and neck",
     .==15 | (. >= 150 & . <160) | (. == 339) ~ "Esophagus/Trachea",
     (. >= 160 & . <220) | (.>= 480 & .<490) | .==762 ~ "Gastrointestinal tract",
     .==22 | (. >= 220 & . <250) ~ "Liver/IHD/Biliary tract",
     .==34 | (. >= 340 & . <349) ~ "Lung/Bronchus",
     (. >= 379 & . <399) | .==761 ~ "Other intrathoracic",
     (. >= 410 & .<419) | (. >= 490 & . < 500) ~ "Sarcoma",
     .==77 | (.>=770 & .<800) ~ "Lymphoma",
     .==42 | (. >= 420 & .<424) ~ "Hematological",
     (.==421) ~ "Hodgkin",
     .==44 | (.>=440 & .< 470) ~ "Skin",
     .==72 | (.>=470 & .<479) | (.>=690 & .<=729)~ "Brain and Nervous System", # including 1 choroid (eye) cancer
     .==50 | (.>=500 & .<510) ~ "Breast",
     (.>=510 & .<=529) | (.==579)~ "Vulva/vagina",
     .==53 | (.>=530 & .< 540) ~ "Cervix",
     .==54 | (.>=540 & .<560) ~ "Uterus",
     (.>=569 & .<=570) | (.==589) ~ "Ovary/Fallopian tube", # note includes 1 placenta
     .>=619 ~ "Prostate",
     .==62 | (.>=60 & .<=619) | (.>=620 & .<639) ~ "Other male genital",
     .>640 & .<690 ~ "Urinary tract", # including kidney
     .==73 | (.>=730 & .<740) ~ "Thyroid",
     (.>=740 & .<760) ~ "Other endocrine",
     # no cases for 762 769 (other undefined)
     #*---------------
     #*
     #*
  
     # morphology ## LATER
    #  across(
    # .cols = contains("_morph"),
    # .fns = ~case_when(
    )
)
)

# create time to event variables

dta2 = dta1 %>% 
   # time to first INVASIVE cancer; do not censor at in situ; death as competing risk; censor at other
  
  tidyr::unite(
  d_lc, c(m_lcontact, y_lcontact), sep = "-", remove = F
  ) %>% 
  tidyr::unite(
  d_livedead, c(m_livedead, y_livedead), sep = "-", remove = F
  ) %>% mutate(
   d_lc = lubridate::parse_date_time(d_lc, "my"),
   d_livedead = lubridate::parse_date_time(d_livedead, "my"),
   # find minimum of invasive, death, or lfy 
   ftime_inv_sec = as.numeric(pmin(d_1st_inv, d_lc, d_livedead, na.rm = T) - ddx), # futime in secs
   ftime_inv_yr = ftime_inv_sec/86400/365.25
   # exclude 139 that have missing l_contact
)

# code to view pts with ftime <0. The first one is an error
View(dta2 %>% filter(ftime_inv_yr < 0) %>% select(ResearchID, ftime_inv_yr, d_1st_inv, y_smn1, m_smn1, y_smn2, y_smn3, y_smn4, d_lc, m_lcontact, y_lcontact, d_livedead, m_livedead, y_livedead, ddx, m_diagnose, y_diagnose
                                                  ))
```
